model_path: C:/Users/chayaphonlamt/Documents/CarParkingMonitor/yolo12s.pt
yolo_model: yolo12s.pt
img_size:
- 960
conf_threshold: 0.45
iou_threshold: 0.45
agnostic_nms: false
max_det: 300
augment: false
reid_model: /weights/model_best.pth
boxmot_config_path: boxmot/configs/deepocsort.yaml
detection_confidence_threshold: 0.1
car_class_id:
- 2
- 5
- 7
tracking_method: deepocsort
per_class_tracking: false
debug_settings:
  enabled: false
  mock_violation_minutes: 1
parking_time_limit_minutes: 15
parking_time_threshold_seconds: 30
grace_period_frames_exit: 30
parked_car_timeout_seconds: 40
movement_threshold_px: 80
movement_frame_window: 120
output_dir: runs/car_parking_monitor_multi_cam
device: cuda
half_precision: true
api_key: nemo1234
display_combined_max_width: 960
display_combined_max_height: 540
queue_max_size: 5
save_video: false
save_mot_results: false
enable_brightness_adjustment: false
brightness_method: histogram
video_sources:
- name: camera_1
  branch: kubon
  source_path: "C:\\Users\\bovornpotpua\\Desktop\\\u0E20\u0E32\u0E1E\u0E41\u0E25\u0E30\
    \u0E2D\u0E37\u0E48\u0E19\u0E46\\example.mp4"
  parking_zone_file: parking_zone_camera1.json
  branch_id: '11970'
  camera_id: "\u0E08\u0E32\u0E01 Video"
- name: camera_2
  branch: "\u0E1A\u0E34\u0E2A\u0E2A\u0E34\u0E40\u0E19\u0E2A\u0E1E\u0E32\u0E23\u0E4C\
    \u0E04 3"
  source_path: rtsp://adminhq:admin1@2@111.197.183.9:554/Streaming/Channels/101
  parking_zone_file: parking_zone_camera2.json
  branch_id: '19783'
  camera_id: "\u0E01\u0E25\u0E49\u0E2D\u0E07 Hikvision"
- name: camera_3
  branch: "\u0E2A\u0E35\u0E14\u0E32-\u0E1A\u0E31\u0E27\u0E43\u0E2B\u0E0D\u0E48"
  source_path: rtsp://adminhq:admin1@2@112.131.146.9:554/cam/realmonitor?channel=1&subtype=0
  parking_zone_file: parking_zone_camera3.json
  branch_id: '23146'
  camera_id: "\u0E01\u0E25\u0E49\u0E2D\u0E07 Dahua"
- name: camera_4
  branch: "\u0E0B\u0E2D\u0E22\u0E15\u0E25\u0E32\u0E14\u0E25\u0E48\u0E32\u0E07 18"
  source_path: rtsp://adminhq:admin1@2@111.140.102.9:554/onvif/profile1/media.smp
  parking_zone_file: parking_zone_camera4.json
  branch_id: '14002'
  camera_id: "\u0E01\u0E25\u0E49\u0E2D\u0E07 Samsung"
performance_settings:
  target_inference_width: 1280
  frames_to_skip: 1
  draw_bounding_box: true
