model_path: C:/Users/chayaphonlamt/Documents/CarParkingMonitor/yolo12s.pt
yolo_model: yolo12s.pt
img_size:
- 960
conf_threshold: 0.45
iou_threshold: 0.45
agnostic_nms: false
max_det: 300
augment: false
reid_model: /weights/model_best.pth
boxmot_config_path: boxmot/configs/deepocsort.yaml
detection_confidence_threshold: 0.1
car_class_id:
- 2
- 5
- 7
tracking_method: deepocsort
per_class_tracking: false
debug_settings:
  enabled: false
  mock_violation_minutes: 1
parking_time_limit_minutes: 15
parking_time_threshold_seconds: 30
grace_period_frames_exit: 30
parked_car_timeout_seconds: 40
movement_threshold_px: 80
movement_frame_window: 120
output_dir: runs/car_parking_monitor_multi_cam
device: cuda
half_precision: true
api_key: nemo1234
display_combined_max_width: 960
display_combined_max_height: 540
queue_max_size: 5
save_video: false
save_mot_results: false
enable_brightness_adjustment: false
brightness_method: histogram
video_sources:
- name: camera_1
  branch: kubon
  source_path: "C:\\Users\\bovornpotpua\\Desktop\\\u0E20\u0E32\u0E1E\u0E41\u0E25\u0E30\
    \u0E2D\u0E37\u0E48\u0E19\u0E46\\example.mp4"
  parking_zone_file: parking_zone_camera1.json
  branch_id: '11970'
  camera_id: D1 F1_11970_BE
- name: camera_2
  branch: kubon
  source_path: C:\Users\USER\Videos\car\kubon_BE (2).mp4
  parking_zone_file: parking_zone_camera2.json
  branch_id: '11970'
  camera_id: D1 F2_11970_BE
performance_settings:
  target_inference_width: 1280
  frames_to_skip: 1
  draw_bounding_box: true
