# config.yaml

# YOLO Model Settings
model_path: C:/Users/chayaphonlamt/Documents/CarParkingMonitor/yolov8m.pt
yolo_model: "yolov8m.pt" # <<< ปรับ: ใช้ yolov8n.pt (nano) ซึ่งเล็กที่สุดและเร็วที่สุดบน CPU
img_size: [1280]          # <<< ปรับ: ลดขนาดภาพที่ป้อนให้โมเดล ถ้าวิดีโอใหญ่กว่านี้จะถูกย่อ
                         #      (Logs เดิมของคุณแสดง 384x640 ซึ่งเล็กอยู่แล้ว ถ้า model.track จัดการดีก็อาจไม่ต้องปรับตรงนี้มาก)
conf_threshold: 0.3
iou_threshold: 0.4

# Re-ID Model Settings (for tracking)
# ควรใช้โมเดล Re-ID ที่เล็กและ optimized สำหรับ CPU หรือฟอร์แมต ONNX/OpenVINO
reid_model: "/weights/model_best.pth" # <<< แนะนำ: ใช้ osnet_x0_25_msmt17.pt แทน model_best.pth เพื่อความเข้ากันได้กับ BoxMOT/Ultralytics
                                     #      และมักจะเป็นโมเดลที่เล็กกว่า (แต่ก็ยังใช้ CPU)

# Path ไปยัง BoxMOT config files (ในโฟลเดอร์ boxmot/configs)
boxmot_config_path: boxmot/configs/deepocsort.yaml

detection_confidence_threshold: 0.3
car_class_id: [2, 5,7] # ตรวจสอบให้แน่ใจว่า class ID เหล่านี้ถูกต้องสำหรับโมเดลของคุณ

# Tracking Method (BoxMOT options)
tracking_method: "deepocsort"
per_class_tracking: False

# # Settings for faster testing
# debug_settings:
#   enabled: true                  # เปิด/ปิด โหมดทดสอบ
#   mock_warning_minutes: 0.5      # แจ้งเตือน Warning ที่ 30 วินาที
#   mock_violation_minutes: 1.0    # แจ้งเตือน Violation (และแคปภาพ) ที่ 1 นาที

# Default Parking Thresholds
parking_time_limit_minutes: 15
warning_time_limit_minutes: 13
parking_time_threshold_seconds: 30 #ถึงจะถือว่า "จอด"
grace_period_frames_exit: 30 # จำนวนเฟรมที่ยอมให้รถออกนอกโซนชั่วคราวได้ก่อนตัดสถานะจอด

# ค่านี้ควรจะนานกว่า 5 วินาทีปกติ เพื่อป้องกัน ID หายเมื่อ Detector มองไม่เห็นชั่วขณะ
parked_car_timeout_seconds: 10 # ตั้งไว้ที่ (ปรับค่าได้ตามต้องการ)

# Movement Detection for Parking
movement_threshold_px: 80.0
movement_frame_window: 120 # ลองลดค่านี้ถ้ายังช้ามาก (เช่น 10-20) แต่จะแม่นยำน้อยลง

# Output Settings
output_dir: "runs/car_parking_monitor_multi_cam"

# Hardware Settings (Main Process and all sub-processes/models)
device: "cuda" # <<< ถูกต้องแล้ว: ใช้ "cpu" เมื่อไม่มี GPU

half_precision: False # <<< ปรับ: ต้องเป็น False เมื่อใช้ CPU (half precision ไม่มีผลบน CPU และอาจทำให้เกิดปัญหา)

# ### FIX: เพิ่ม API Key สำหรับการยืนยันตัวตนกับ Backend ###
api_key: "nemo1234" # ต้องเป็นค่าเดียวกับที่ตั้งไว้ใน main.py

# Display Settings (ตอนนี้ใช้สำหรับแต่ละหน้าต่างกล้อง)
display_combined_max_width: 960 # <<< ปรับ: ลดขนาดสูงสุด เพื่อให้แต่ละหน้าต่างไม่ใหญ่เกินไป
display_combined_max_height: 540 # <<< ปรับ: ลดขนาดสูงสุด เพื่อให้แต่ละหน้าต่างไม่ใหญ่เกินไป

# Multiprocessing Queue Settings
queue_max_size: 5 # <<< ปรับ: ลองลดขนาด Queue เพื่อประหยัด RAM ในแต่ละ Process

# Global flags for saving (ใช้ใน worker processes)
save_video: False        # <<< เพิ่ม: ควบคุมการบันทึกวิดีโอ (เปลี่ยนเป็น True ถ้าต้องการ)
save_mot_results: False  # <<< เพิ่ม: ควบคุมการบันทึกผล MOT (เปลี่ยนเป็น True ถ้าต้องการ)

# Brightness Adjustment (เพิ่มเข้ามาตามโค้ดที่คุณมี)
enable_brightness_adjustment: True # เปลี่ยนเป็น True ถ้าต้องการปรับความสว่าง
brightness_method: clahe            # clahe หรือ histogram

# Multiple Video Sources Configuration
video_sources:
  - name: "petchhome_cam"
    # แก้ไข path นี้ให้ถูกต้อง
    branch: "ซอยตั้งสิน"
    source_path: "C:/Users/Loq/Documents/ai_nemo/ซอยตั้งสิน_BG_19486 (1).mp4"
    parking_zone_file: "parking_zone_camera1.json"
    branch_id: "11818_BN"
    camera_id: "F1_11818_BN"

  - name: "petchhome1_cam"
    # แก้ไข path นี้ให้ถูกต้อง
    branch: "ซอยตั้งสิน_BG_19486"
    source_path: "C:/Users/Loq/Documents/ai_nemo/ซอยตั้งสิน_BG_19486 (2).mp4"
    parking_zone_file: "parking_zone_camera2.json"
    branch_id: "19662_RSL"
    camera_id: "F2_19662_RSL"


# Performance Settings for CPU (and relevant for Edge Devices too)
performance_settings:
  # ความกว้างของเฟรมที่จะใช้ส่งเข้าโมเดล YOLO และ Tracker
  # ยิ่งค่าน้อยลง ยิ่งเร็วขึ้น แต่ความแม่นยำอาจลดลงสำหรับวัตถุเล็กๆ
  # แนะนำให้ลอง: 640 (มาตรฐาน), 480, 320
  target_inference_width: 640 

  # จำนวนเฟรมที่จะข้ามก่อนประมวลผล
  # 1: ไม่ข้ามเฟรมเลย (ประมวลผลทุกเฟรม)
  # 2: ประมวลผลทุกๆ เฟรมที่ 2 (ข้าม 1 เฟรม)
  # 3: ประมวลผลทุกๆ เฟรมที่ 3 (ข้าม 2 เฟรม)
  # ยิ่งค่าสูงขึ้น ยิ่งเร็วขึ้น แต่ภาพจะกระตุกและอาจพลาดเหตุการณ์สำคัญ
  frames_to_skip: 1 
  draw_bounding_box: True     
